postgres:
  host: 192.168.99.100
  port: 5432
  username: postgres
  password: secretpass
  dbname: postgres

poloniex:
  key: YOUR_API_KEY
  secret: YOUR_API_SECRET

trading:
  fiat: BTC
  interval: 86400  # 1 day
